### ISSUE TITLE
WP version 4.9 mistakenly detected

### ISSUE THREAD

**Issue by bfintal** [kallookoo/wp-color-picker-alpha#21]
If you have the plugin NextGen gallery installed, it sets the property `wpColorPickerL10n.current` which prompts the script to detect the WP version as < 4.9. Because of this all colorpickers wouldn't appear.

Other properties that can be used in conjuction with this check might be `clearAriaLabel` and `defaultAriaLabel`. Reference: https://core.trac.wordpress.org/ticket/39662

https://github.com/gambitph/Titan-Framework/issues/413

**Comment by kallookoo** [comment]
Hi,
The NextGEN Gallery plugin makes a very bad practice because it overwrites the variable wpColorPickerL10n.
It is not a question of how I detect the WordPress version.
If you look at source code it is clearly seen two definitions of the variable and as we know the last is the one that is valid.

Create an issue with them so they can do it better.
