### ISSUE TITLE
GPL licensing

### ISSUE THREAD

**Issue by jonmarkhall** [kallookoo/wp-color-picker-alpha#27]
Hi there,
Is it possible to license this project under the GPLv2 "or later" instead of only v2 as it appears to be currently? I am no expect on legal and licensing matters but this change would make me more comfortable potentially using this script in a GPLv3+ project.

Thanks!

**Comment by kallookoo** [comment]
Hi @jonmarkhall 
Use version 2 since both Iris and WordPress are the ones that they use.
As I do not really use your code, I change it to 3. ;)

**Comment by aristath** [comment]
Since this script was changed to GPLv3, WordPress themes and plugins released under the GPLv2 can no longer use the script. Since Apr.11 this can only be used in products licenced under the GPLv3 or above.
v3 is not better than v2, they are different licenses and though they are forwards-compatible they are not backwards-compatible.
Changing the license to "GPLv2 or above" would cover all cases.

**Comment by jonmarkhall** [comment]
Also, the licensing info in the JS files has not been updated

**Comment by aristath** [comment]
> Also, the licensing info in the JS files has not been updated

Which is what allowed me to use the script on my theme 👍

**Comment by kallookoo** [comment]
@aristath The GPL 2 or 3 **only** are not compatible, but WordPress use GPL2 or later. 
Therefore, this script is compatible, or at least I understand it because I am not a lawyer.
See https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

I will also change it to the same one that uses WordPress since I see that it produces confusion.
