### ISSUE TITLE
jQuery compatibility issues

### ISSUE THREAD

**Issue by ioannup** [kallookoo/wp-color-picker-alpha#47]
Enable SCRIPT_DEBUG constant in the wp-config.php file, and check the browser console after selecting a color:
 - `JQMIGRATE: jQuery.fn.change() event shorthand is deprecated`
 - `JQMIGRATE: jQuery.isFunction() is deprecated`

**Comment by kallookoo** [comment]
Hi, @ioannup 

After checking it in version 5.8.3 of WordPress and eliminating the warnings, I see that there are more but they are caused by the original files and I have no control over them, apart from this, this script tries to be as compatible as possible by modifying what is strictly necessary.

**Comment by ioannup** [comment]
Hey @kallookoo !
I guess they already fixed WP core issues, because I checked on (5.9-RC1) and only noticed these 2 issues.

**Comment by ioannup** [comment]
oh, you've already added a fix. Thanks a lot, bro!

**Comment by kallookoo** [comment]
Ok, I close it!
