### ISSUE TITLE
Can't select #000000 on color picker

### ISSUE THREAD

**Issue by gerardreches** [kallookoo/wp-color-picker-alpha#51]
I don't seem to be able to choose pitch black (#000000) when using the alpha color picker.

The darkest color I can choose is #0a0a0a. 

I can write #000000 in the input field, but I can't choose it in the color picker.

**Comment by kallookoo** [comment]
This is and bug described in the Iris repository, see:
- https://github.com/Automattic/Iris/issues/27
- https://github.com/Automattic/Iris/pull/48

I think the best solution would be to set the [containment](https://api.jqueryui.com/draggable/#option-containment) with the x and y values, but as this script (>= v3) tries to overwrite the methods as little as possible, I have to study the best way to do it.

**Comment by gerardreches** [comment]
Hi @kallookoo , I see. I've tried to mention those issues in the WordPress slack to try to get someone to take a look into it. Woud there be any way to work around it?

**Comment by kallookoo** [comment]
Hello,

From my point of view the only viable option for everyone is for @Automattic to update Iris at once.

Some of the solutions proposed could be implemented but for the moment I just want to overwrite what is necessary to maintain the best possible compatibility.

You could use the CSS solution for your projects since it is easier to maintain it in case of future changes.
